on:
  pull_request:
    branches:
      - main

  workflow_dispatch:
  
  workflow_call:

name: Build

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: '8.14.1'

      - name: Setup Gradle Wrapper
        run: gradle wrapper --distribution-type all

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload libs
        uses: actions/upload-artifact@v7
        with:
          name: build_libs
          path: ./build/libs/**
